#!/usr/bin/env python3
"""
Rebuild schools/schools-of-emotion/grammar.json — the constellation.

WHY THIS SCRIPT EXISTS. The constellation is the L3 root -> L2 branch -> L1
school tree, and it is what viewers/genealogy-tree.html ("Tree of Life") loads
by default. It used to be hand-authored, and it went stale the way hand-authored
indexes always do: it was written when the library had seven branches and one
school, and it still said so long after the library had grown to twelve branches
and twenty-eight schools. The Tree of Life spent that whole time quietly showing
a map of a library that no longer existed — including no House School at all,
which is where the maintainer's own work lives.

So it is derived now. schools/_collection.json is the one place branches are
declared; everything here is read from it, and from each school's own grammar:

  branch name + prose  <- _collection.json branches[].name / ._note
  which schools it has <- _collection.json branches[].school_slugs
  school name          <- that school's grammar.json `name`
  what a school is     <- that school's grammar.json `description`
  its evidence tier    <- that school's root item's metadata.evidence_tier/_note
  the link target      <- that school's root item id

Nothing in this file is a second copy of anything. Add a school to a branch in
_collection.json and the constellation grows to match on the next build; there
is no second edit to forget.

WHAT IS STILL HAND-AUTHORED: the top-level block of the output file — its
`name`, `description`, tags and `_grammar_commons` attribution. Those are read
from the existing file and passed through untouched, so editing them by hand is
correct and safe. Only `items` is generated. Branch prose is hand-written too,
but it lives in _collection.json's `_note` fields, which is where a branch is
declared in the first place.

Usage:  python scripts/build_constellation.py [--check]
        --check exits non-zero if the file on disk is stale, without writing.
        check_all.py runs it that way, so drift fails the pre-commit gate
        instead of going unnoticed for another few hundred commits.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
SCHOOLS = os.path.join(ROOT, "schools")
OUT_SLUG = "schools-of-emotion"
OUT = os.path.join(SCHOOLS, OUT_SLUG, "grammar.json")
COLLECTION = os.path.join(SCHOOLS, "_collection.json")

# Not schools in the constellation's sense: the aggregator is a generated pool,
# and the constellation cannot contain itself.
SKIP = {"across-the-schools", OUT_SLUG}

GENERATED_NOTE = (
    "Generated by scripts/build_constellation.py from schools/_collection.json — "
    "do not hand-edit the items. To change what the constellation shows, edit the "
    "branches in _collection.json (their names, notes and school_slugs) or the "
    "school's own grammar, and rebuild. The top-level name, description, tags and "
    "attribution below ARE hand-authored and are passed through untouched."
)


def load(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def root_item_of(grammar):
    """A school's root item — the link target, and where its evidence tier lives."""
    roots = [i for i in grammar.get("items", []) if i.get("category") == "root"]
    if roots:
        return roots[0]
    # Fall back to the deepest item, the same way the tree viewer finds a root.
    by_level = sorted(grammar.get("items", []), key=lambda i: i.get("level", 1))
    return by_level[-1] if by_level else None


def build():
    coll = load(COLLECTION)
    existing = load(OUT) if os.path.isfile(OUT) else {}

    items = []
    branch_ids = []
    missing = []

    for b_order, branch in enumerate(coll.get("branches", []), start=1):
        bid = branch["id"]
        link_ids = []

        for s_order, slug in enumerate(branch.get("school_slugs", []), start=1):
            if slug in SKIP:
                continue
            gpath = os.path.join(SCHOOLS, slug, "grammar.json")
            if not os.path.isfile(gpath):
                missing.append(f"{bid}: no such school '{slug}'")
                continue
            g = load(gpath)
            root = root_item_of(g)
            if root is None:
                missing.append(f"{slug}: no items, cannot link")
                continue

            sections = {"What it is": g.get("description", "").strip()}
            md = root.get("metadata") or {}
            tier, note = md.get("evidence_tier"), md.get("evidence_note")
            if tier:
                # The tier and its note are carried whole rather than summarised.
                # An undifferentiated "evidence-based" badge is the thing this
                # library exists to refuse, so the caveat travels with the claim.
                sections["Evidence"] = (
                    f"Held at evidence tier '{tier}'."
                    + (f" {note.strip()}" if note else "")
                )

            link_id = f"link-{slug}"
            link_ids.append(link_id)
            items.append({
                "id": link_id,
                "name": g.get("name", slug),
                "category": "school-link",
                "level": 1,
                "sort_order": b_order * 100 + s_order,
                "sections": sections,
                "keywords": (g.get("tags") or [])[:6],
                "metadata": {
                    "source_deck": slug,
                    "source_item_id": root["id"],
                    "deck": g.get("name", slug),
                    "branch_id": bid,
                },
            })

        branch_id = f"branch-{bid}"
        branch_ids.append(branch_id)
        branch_item = {
            "id": branch_id,
            "name": branch.get("name", bid),
            "category": "branch",
            "level": 2,
            "sort_order": b_order,
        }
        if link_ids:
            branch_item["composite_of"] = link_ids
        prose = (branch.get("_note") or "").strip()
        # An empty branch is left visible on purpose — a placeholder for work not
        # yet done rather than something hidden. That was the hand-authored file's
        # stated intent and it is preserved here.
        if not link_ids:
            prose = (prose + " No school is built in this branch yet.").strip()
        branch_item["sections"] = {"What this branch is": prose}
        branch_item["metadata"] = {"branch_id": bid}
        items.append(branch_item)

    n_branches, n_schools = len(branch_ids), sum(
        1 for i in items if i["category"] == "school-link")
    items.append({
        "id": f"{OUT_SLUG}-root",
        "name": existing.get("name", "Schools of Emotion"),
        "category": "root",
        "level": 3,
        "sort_order": 1000,
        "composite_of": branch_ids,
        "sections": {
            "What this is": (
                f"The constellation as it currently stands: {n_schools} schools in "
                f"{n_branches} branches, sitting on a constructionist substrate rather "
                "than on any one branch's claim to have found emotion's true shape. "
                "This is a handful of the ways people have organised feeling, not a "
                "catalogue of them — the library could not hold them all, and does not "
                "claim to. Open a branch to see its schools; open a school to draw from "
                "it directly."
            )
        },
        "keywords": ["schools of emotion", "constellation", "recursive repatterning"],
    })

    # Pass the hand-authored top-level block through untouched; replace only items.
    out = {k: v for k, v in existing.items() if k != "items"}
    out["_note"] = GENERATED_NOTE
    out["_generated"] = True
    out["items"] = items
    return out, missing


def main():
    check = "--check" in sys.argv
    built, missing = build()

    for m in missing:
        print(f"WARNING: {m}")

    existing = load(OUT) if os.path.isfile(OUT) else None
    changed = existing != built
    n_b = sum(1 for i in built["items"] if i["category"] == "branch")
    n_s = sum(1 for i in built["items"] if i["category"] == "school-link")
    summary = f"{n_b} branches, {n_s} schools"

    if check:
        if changed:
            print("STALE — run `python scripts/build_constellation.py` and commit the result")
            return 1
        print(f"up to date: {summary}")
        return 0

    if changed:
        os.makedirs(os.path.dirname(OUT), exist_ok=True)
        with open(OUT, "w", encoding="utf-8") as fh:
            json.dump(built, fh, ensure_ascii=False, indent=2)
            fh.write("\n")
        print(f"wrote {os.path.relpath(OUT, ROOT)}: {summary}")
    else:
        print(f"up to date: {summary}")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
